import pygame
player_image=pygame.image.load("image/player/player.png").convert_alpha()
player_bullet=pygame.image.load("image/player/player bullet.png").convert_alpha()
enemy_image=pygame.image.load("image/enemy/enemy.png").convert_alpha()
enemy_bullet=pygame.image.load("image/enemy/enemy bullet.png").convert_alpha()
brick_image=pygame.image.load("image/blocks/brick block.png").convert_alpha()
iron_image=pygame.image.load("image/blocks/iron block.png").convert_alpha()
bush_image=pygame.image.load("image/blocks/bush block.png").convert_alpha()
water_image=pygame.image.load("image/blocks/water block.png").convert_alpha()
flag_image=pygame.image.load("image/blocks/flag.png").convert_alpha()
game_over=pygame.image.load("image/dop/game over.png").convert_alpha()